<?xml version="1.0"?>

<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Constants -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    
    <!-- Dummy inertia -->
    <xacro:property name="dummy_inertia"                value="1e-09"/>   

    <!-- Classic parameters -->
    <xacro:property name="body_mass"    value="10"/>
    <xacro:property name="body_lenght"  value="0.7"/>
    <xacro:property name="body_width"   value="0.4"/>
    <xacro:property name="body_height"  value="0.3"/>

    <!-- Front wheel parameters -->
    <xacro:property name="front_wheel_mass"     value="0.001"/>
    <xacro:property name="front_wheel_radius"   value="0.05"/>

    <!-- Rear wheel parameters -->
    <xacro:property name="rear_wheel_mass"      value="0.001"/>
    <xacro:property name="rear_wheel_radius"    value="0.05"/>

    <!-- Control wheels parameters -->
    <xacro:property name="control_wheel_mass"   value="2"/>
    <xacro:property name="control_wheel_radius" value="0.1"/>
    <xacro:property name="control_wheel_lenght" value="0.1"/>

    <!-- Frame position and orientation -->
    <xacro:property name="right_wheel_frame_position"       value="0 ${-body_width/2 - control_wheel_lenght/2} 0"/>
    <xacro:property name="right_wheel_frame_orientation"    value="${-PI/2} 0 0"/>
    <xacro:property name="left_wheel_frame_position"        value="0 ${body_width/2 + control_wheel_lenght/2} 0"/>
    <xacro:property name="left_wheel_frame_orientation"     value="${-PI/2} 0 0"/>
    <xacro:property name="front_wheel_frame_position"       value="${body_lenght/2 - 2 * front_wheel_radius} 0 ${-front_wheel_radius}"/>
    <xacro:property name="front_wheel_frame_orientation"    value="0 0 0"/>
    <xacro:property name="rear_wheel_frame_position"        value="${-body_lenght/2 + 2 * rear_wheel_radius} 0 ${-rear_wheel_radius}"/>
    <xacro:property name="rear_wheel_frame_orientation"     value="0 0 0"/>
    <xacro:property name="laser_frame_position"             value="0 0 ${body_height + 0.02}"/>
    <xacro:property name="laser_frame_orientation"          value="0 0 0"/>
    <xacro:property name="imu_frame_position"               value="0 0 ${body_height/2}"/>
    <xacro:property name="imu_frame_orientation"            value="0 0 0"/>

    <!-- Import Rviz colors -->
    <xacro:include filename="$(find my_robot)/robot_description/materials.xacro"/>

    <!-- Import Gazebo customization elemets -->
    <xacro:include filename="$(find my_robot)/robot_description/robot_description.gazebo"/>

    <!-- Import laser sensor -->
    <xacro:include filename="$(find my_robot)/sensors/hokuyo.urdf.xacro"/>

    <!-- Import IMU sensor -->
    <xacro:include filename="$(find my_robot)/sensors/imu.urdf.xacro"/>

    <!-- Extra link (non-inertial) -->
    <link name="base_footprint" />
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <!-- Chassis Link -->
    <link name="base_link">
        <collision>
            <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${body_lenght} ${body_width} ${body_height}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${body_lenght} ${body_width} ${body_height}"/>
            </geometry>
            <material name="green"/>
        </visual>

        <inertial>
            <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
            <mass value="${body_mass}"/>
            <inertia
                ixx="${body_mass / 12 * (body_width*body_width + body_height*body_height)}" ixy="0.0" ixz="0.0"
                iyy="${body_mass / 12 * (body_height*body_height + body_lenght*body_lenght)}" iyz="0.0"
                izz="${body_mass / 12 * (body_lenght*body_lenght + body_width*body_width)}"/>
        </inertial>
    </link>

     <!-- IMU link -->
    <xacro:imu xyz="${imu_frame_position}" 
        rpy="${imu_frame_orientation}"
        parent="base_link">
    </xacro:imu>

    <!-- Laser link -->
    <xacro:hokuyo_laser xyz="${laser_frame_position}" 
        rpy="${laser_frame_orientation}" 
        parent="base_link">
    </xacro:hokuyo_laser>

    <!-- Right wheel joint -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="${right_wheel_frame_position}" rpy="${right_wheel_frame_orientation}"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.7"/>
    </joint>

    <!-- Right wheel link -->
    <link name="right_wheel">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${control_wheel_lenght}" radius="${control_wheel_radius}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${control_wheel_lenght}" radius="${control_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${control_wheel_mass}"/>
            <inertia
                ixx="${control_wheel_mass / 12 * (3 * control_wheel_radius*control_wheel_radius + control_wheel_lenght*control_wheel_lenght)}" ixy="0.0" ixz="0.0"
                iyy="${control_wheel_mass / 12 * (3 * control_wheel_radius*control_wheel_radius + control_wheel_lenght*control_wheel_lenght)}" iyz="0.0"
                izz="${control_wheel_mass /  2 * (control_wheel_radius*control_wheel_radius)}"/>  
        </inertial>
    </link>

    <!-- Left wheel joint -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="${left_wheel_frame_position}" rpy="${left_wheel_frame_orientation}"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.7"/>
    </joint>

    <!-- Left wheel link -->
    <link name="left_wheel">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${control_wheel_lenght}" radius="${control_wheel_radius}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${control_wheel_lenght}" radius="${control_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${control_wheel_mass}"/>
            <inertia
                ixx="${control_wheel_mass / 12 * (3 * control_wheel_radius*control_wheel_radius + control_wheel_lenght*control_wheel_lenght)}" ixy="0.0" ixz="0.0"
                iyy="${control_wheel_mass / 12 * (3 * control_wheel_radius*control_wheel_radius + control_wheel_lenght*control_wheel_lenght)}" iyz="0.0"
                izz="${control_wheel_mass /  2 * (control_wheel_radius*control_wheel_radius)}"/>  
        </inertial>
    </link>

    <!-- Rear wheel joint -->
    <joint name="rear_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_wheel"/>
        <origin xyz="${rear_wheel_frame_position}" rpy="${rear_wheel_frame_orientation}"/>
    </joint>

    <!-- Rear wheel link -->
    <link name="rear_wheel">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${rear_wheel_radius}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${rear_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${rear_wheel_mass}"/>
            <inertia
                ixx="${2 * rear_wheel_mass * rear_wheel_radius * rear_wheel_radius / 5}" ixy="0.0" ixz="0.0"
                iyy="${2 * rear_wheel_mass * rear_wheel_radius * rear_wheel_radius / 5}" iyz="0.0"
                izz="${2 * rear_wheel_mass * rear_wheel_radius * rear_wheel_radius / 5}"/>  
        </inertial>
    </link>

    <!-- Front wheel joint -->
    <joint name="front_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_wheel"/>
        <origin xyz="${front_wheel_frame_position}" rpy="${front_wheel_frame_orientation}"/>
    </joint>

    <!-- Front wheel link -->
    <link name="front_wheel">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${front_wheel_radius}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${front_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${front_wheel_mass}"/>
            <inertia
                ixx="${2 * front_wheel_mass * front_wheel_radius * front_wheel_radius / 5}" ixy="0.0" ixz="0.0"
                iyy="${2 * front_wheel_mass * front_wheel_radius * front_wheel_radius / 5}" iyz="0.0"
                izz="${2 * front_wheel_mass * front_wheel_radius * front_wheel_radius / 5}"/>  
        </inertial>
    </link>

    <!-- Transmission at joints-->
    <transmission name="right_wheel_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_wheel_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_wheel_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction></mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="left_wheel_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_wheel_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_wheel_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction></mechanicalReduction>
        </actuator>
    </transmission>

</robot>