# Numero complessivo di agenti
n_robot: 3

#  Lista di dizionari conteneni ID e coordinate degli waypoints
waypoints:

- id: 0
  x: 0
  y: 0

- id: 1
  x: 1
  y: 0

- id: 2
  x: 1
  y: 1

waypoints_new:
  '1': [-1,10]
  '2': [3,2]
  '3': [-4,5]