# Numero complessivo di agenti
n_robot: 4

# #  Lista di dizionari conteneni ID e coordinate degli waypoints
# waypoints:

# - id: 0
#   x: 0
#   y: 0

# - id: 1
#   x: 1
#   y: 0

# - id: 2
#   x: 1
#   y: 1

waypoints_new:
  '1': [0,2]
  '2': [-4,1]
  '3': [3,2]
  '4': [-3,3]
  '5': [-1,5]
  '6': [-4,6]
  '7': [3,6]
  '8': [2,4]
  '9': [5,4]
  '10': [1,1]
  '11': [5,1]
  '12': [-2,2]
  '13': [-5,4]
  '14': [-1,4]
  '15': [-3,5]
  '16': [4,4]
  '17': [5,6]
  '18': [1,6]